name: Build and Test

on: push

jobs:

  Ubuntu-Bionic:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:bionic

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Where am I
        run: |
          pwd
          ls -la
